---
output: html_document
---

One limitation of a liquid-liquid extraction is that it is difficult to separate solutes with similar chemical properties as they are likely to have similar distribution ratios. An alternative approach is a countercurrent extraction, which is illustrated in the figure on the lower right. 

Imagine a linear array of tubes, each with an equal volume of phase *a* and labeled sequentially beginning with tube 0 that contains a solute we wish to extract. We add a portion of phase *b* to tube 0. At this point---which we call step 0---the solute is present only in phase *a* of tube 0; thus, its fraction in phase *a* is 1 and its fraction in tube 0 is 1. 

Next we shake tube 0 and extract a fraction *p* into phase *b* and retain a fraction *q* in phase *a*. We then transfer, or shift, the phase *b* in tube 0 to tube 1 and add a fresh portion of phase *b* to tube 0. At the end of the first step, tube 0 contains a fraction *q* of the solute and tube 1 contains a fraction *p* of the solute.

This process of extracting the solute between phases *a* and *b*, and shifting phase *b* down the line of tubes continues. At the end of the second step, tube 0 contains a fraction *q*^2^ of the solute, tube 1 contains a fraction 2*pq* of the solute, and tube 2 contains a fraction *p*^2^ of the solute. The pattern in these fractional amounts follows a binomial distribution

$$ f(r,n) = \frac{n!}{(n - r)!r!}p^rq^{n-r}$$

where $f(r,n)$ is the fraction of solute in tube *r* at the end of step *n*.

You can observe the progress of a separation of two solutes by using the sliders to set their distribution ratios and using the slider to observe the separation at different steps. Clicking on the step slider's play button provides an animated view of the separation process. 

We are limited in this simulation to 100 tubes and steps, but given a sufficient number of tubes and steps, we can separate any mixture of two (or more) solutes as long as there is a difference in their distribution ratios. As a method for separating solutes, a countercurrent apparatus is impractical; it is, however, a useful model for a chromatographic separation where phase *a* remains stationary in a column and phase *b* is mobile and moves through the stationary phase.
