---
output: html_document
---

<!-- The following script makes it possible to use the mhchem -->
<!-- latex package in a .Rmd file and to knit it into an .html file -->
<!-- the font size is scaled to 90% to match text -->

```{=html}
<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  TeX: {
    extensions: ["[Contrib]/mhchem/mhchem.js"]
}
});
MathJax.Hub.Config({ 
        "HTML-CSS": { scale: 90 }, 
        SVG: { linebreaks: { automatic:true } }, 
 });
</script>
```

<!-- text for introduction -->

One limitation of a liquid-liquid extraction is that it is difficult to separate solutes with similar chemical properties as they are likely to have similar solubilities in the two liquid phases. Another approach is a countercurrent extraction (CCE), illustrated in the figure on the right. 

#### Step 0: Intial Set-Up

Imagine a linear array of tubes labeled from tube 0 to tube $n$. Each tube holds an equal volume of a solvent that contains a solute we wish to extract into a different solvent. We add a portion of the second solvent to tube 0. Because the solvents are immiscible, one is layered below the other; we call these solvents the lower phase and the upper phase. At this point---which we call step 0---the solute is present only in the lower phase of tube 0; thus, its fraction in the lower phase is 1 and its fraction in tube 0 is 1. This is the state of the system at the top of the figure.

#### Step 1: Shake, Extract, and Shift

Next we shake tube 0 and extract a fraction *p* of the solute into the upper phase and retain a fraction $q = 1 - p$ of the solute in the lower phase. We then transfer, or shift, the upper phase from tube 0 to tube 1 and add a fresh portion of the upper phase to tube 0. At the end of the first step, tube 0 contains a fraction *q* of the solute and tube 1 contains a fraction *p* of the solute. This is the state of the system at the middle of the figure.

#### Step 2: Repeat Shake, Extract, and Shift

This process of extracting the solute between the lower phase and the upper phase, and shifting the upper phase down the line of tubes continues. At the end of the second step, tube 0 contains a fraction $q^2$ of the solute, tube 1 contains a fraction $2pq$ of the solute, and tube 2 contains a fraction $p^2$ of the solute. This is the state of the system at the bottom of the figure. 

#### Stationary and Mobile Phases

Did you notice the difference in how we describe the two phases? Our description of the upper phase is active in that we transfer, or shift it down the line of tubes. Our description of the lower phase, however, is passive in that the lower phase always remains in its original tube. The lower phase is stationary and the upper phase is mobile, terms we will encounter in modules on chromatographic methods of analysis.
